<a href="https://colab.research.google.com/github/VedJ13/NumPy/blob/main/NumPy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Array Operations

In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
print("Basic slicing",arr[2:7])
print("With Step: ", arr[1:8:2])
print("Negative Indexing : ", arr[-3])

Basic slicing [2 3 4 5 6]
With Step:  [1 3 5 7]


In [5]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print("Specific Element :", arr[2,0])
print("Entire row :", arr[0])
print("Entire column :", arr[:, 2])

Specific Element : 7
Entire row : [1 2 3]
Entire column : [3 6 9]


### Sorting

In [10]:
unsorted = np.array([3,5,3,5,6,21,2,1])
print("Sorted array ", np.sort(unsorted))

arr_2d_unsorted = np.array([[5,2], [3,5], [8,4]])
print("Sorted 2D array by column ", np.sort(arr_2d_unsorted, axis = 0))
print("Sorted 2D array by row ", np.sort(arr_2d_unsorted, axis = 1))

Sorted array  [ 1  2  3  3  5  5  6 21]
Sorted 2D array by column  [[3 2]
 [5 4]
 [8 5]]
Sorted 2D array by row  [[2 5]
 [3 5]
 [4 8]]


## Filter


In [12]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even no. ", even_number)

Even no.  [ 2  4  6  8 10]


## Filter with Mask

In [14]:
mask = numbers < 7
print("Numbers less than 7 ", numbers[mask])

Numbers less than 7  [1 2 3 4 5 6]


## Fancy indexing vs. np.where()

In [15]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result) # returns array with indices for which the condition is true.
print("NP where ", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where  [ 6  7  8  9 10]


In [16]:
condition_array = np.where(numbers > 5, numbers * 2, numbers)
# condition_array = np.where(numbers > 5, "true", "false")
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


## Adding and Removing Data

In [17]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


## Array Compatibility

In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print("Compatibility Shapes : ", a.shape == b.shape)

Compatibility Shapes :  True


In [22]:
original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)

new_col = np.array([[7], [9]])
with_new_column = np.hstack((original,new_col))
print("With new column ",with_new_column)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column  [[1 2 7]
 [3 4 9]]


In [23]:
arr = np.array([1,2,3,4])
deleted = np.delete(arr, 2)
print("Array after deltetion : ", deleted)

Array after deltetion :  [1 2 4]
