<a href="https://colab.research.google.com/github/VedJ13/NumPy/blob/main/NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy


In [2]:
import numpy as np

In [ ]:
arr_1d = np.array([1,2,3,4,5])
print("1d Array : ", arr_1d)

1d Array :  [1 2 3 4 5]


In [ ]:
arr_2d = np.array([[1,2,3], [4,5,6]])
print("2d Array : ", arr_2d)

2d Array :  [[1 2 3]
 [4 5 6]]


## List vs numpy array



In [ ]:
py_list = [1,2,3] # Replicate the list n times
print("Python list multiplication : ",py_list * 2)

Python list multiplication :  [1, 2, 3, 1, 2, 3]


In [ ]:
np_array = np.array([1,2,3]) # element wise multiplication
print("Python numpy multiplication : ",np_array * 2)

Python list multiplication :  [2 4 6]


In [ ]:
import time
start = time.time()
py_list = (i*2 for i in range(1000000))
print("\n List operation time : ",time.time() - start)

start = time.time()
np_array = np.arange(1000000)
print("\n NumPy operation time : ",time.time() - start)


 List operation time :  0.00017571449279785156

 NumPy operation time :  0.007056713104248047


### Creating Array from Scratch

In [ ]:
zeros = np.zeros((3,4))
print("zeros array : \n", zeros)

ones = np.ones((3,5))
print("ones array : \n", ones)

full = np.full((3,3), 7)
print("full array : \n", full)

random = (np.random.random((2,3)) * 10).astype(int)
print("random array : \n", random)

sequence = np.arange(0, 10, 2)
print("sequnce array : \n", sequence)

zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array : 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
full array : 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
random array : 
 [[7 3 1]
 [3 6 4]]
sequnce array : 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [ ]:
vector = np.array([1, 2, 3, 4, 5])
print("vector : ", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("matrix : ", matrix)

tensor = np.array(([[[1, 2], [3, 4]],
                    [[5, 6], [7, 8]]]))
print("tensor array : ", tensor)

vector :  [1 2 3 4 5]
matrix :  [[1 2 3]
 [4 5 6]]
tensor array :  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [ ]:
arr = np.array([[1, 2, 3],
               [4, 5, 6]])
print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("DType", arr.dtype)

Shape (2, 3)
Dimension 2
Size 6
DType int64


### Array Reshaping

In [7]:
arr = np.arange(12)
print("Original array : ", arr)

reshaped = arr.reshape([3,4])
print("\n Reshaped array ", reshaped)

# flattened returns copy
flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# ravel {returns view, instead of copy}
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)

Original array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
