<a href="https://colab.research.google.com/github/VedJ13/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("1d Array : ", arr_1d)

1d Array :  [1 2 3 4 5]


In [3]:
arr_2d = np.array([[1,2,3], [4,5,6]])
print("2d Array : ", arr_2d)

2d Array :  [[1 2 3]
 [4 5 6]]


## List vs numpy array



In [8]:
py_list = [1,2,3] # Replicate the list n times
print("Python list multiplication : ",py_list * 2)

Python list multiplication :  [1, 2, 3, 1, 2, 3]


In [9]:
np_array = np.array([1,2,3]) # element wise multiplication
print("Python list multiplication : ",np_array * 2)

Python list multiplication :  [2 4 6]


In [14]:
import time
start = time.time()
py_list = (i*2 for i in range(1000000))
print("\n List operation time : ",time.time() - start)

start = time.time()
np_array = np.arange(1000000)
print("\n NumPy operation time : ",time.time() - start)


 List operation time :  0.00017571449279785156

 NumPy operation time :  0.007056713104248047


### Creating Array from Scratch

In [34]:
zeros = np.zeros((3,4))
print("zeros array : \n", zeros)

ones = np.ones((3,5))
print("ones array : \n", ones)

full = np.full((3,3), 7)
print("full array : \n", full)

random = (np.random.random((2,3)) * 10).astype(int)
print("random array : \n", random)

sequence = np.arange(0, 10, 2)
print("sequnce array : \n", sequence)

zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array : 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
full array : 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
random array : 
 [[7 3 1]
 [3 6 4]]
sequnce array : 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [38]:
vector = np.array([1, 2, 3, 4, 5])
print("vector : ", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("matrix : ", matrix)

tensor = np.array(([[[1, 2], [3, 4]],
                    [[5, 6], [7, 8]]]))
print("tensor array : ", tensor)

vector :  [1 2 3 4 5]
matrix :  [[1 2 3]
 [4 5 6]]
tensor array :  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [40]:
arr = np.array([[1, 2, 3],
               [4, 5, 6]])
print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("DType", arr.dtype)

Shape (2, 3)
Dimension 2
Size 6
DType int64
